ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<p>',views.add_to_cart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<p>',views.cart_remove,name="cart_remove"),
    path('full_remove/<p>',views.full_remove,name="full_remove"),
    path('orderform', views.orderform, name="orderform"),
    path('orderview', views.orderview, name="orderview"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('search/',include('search.urls')),
]

if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
path('search',views.search,name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
path('',views.allcategories,name="allcat"),
    path('allproducts/<p>',views.allproducts,name="allproducts"),
    path('detail/<p>',views.detail,name="detail"),
    path('reg',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    address=models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    date_ordered=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/categories', blank=True, null=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    image = models.ImageField(upload_to='shop/products', blank=True, null=True)
    price= models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart
from cart.models import Account,Order
def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.product.price

    except:
        pass

    return render(request,'cart.html',{'c':cart,'total':total})



@login_required
def add_to_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=product)
        if(cart.quantity<cart.product.stock):
             cart.quantity+=1
        cart.save()
    except: #if not add a new record to the cart
        cart = Cart.objects.create(product=product, user=u, quantity=1)
        cart.save()  # both datas added to cart table



    return redirect('cart:cartview')
def cart_remove(request,p):
    p=Product.objects.get(name=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=p)
        if cart.quantity>1:
            cart.quantity-=1

            cart.save()
        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cartview')


def full_remove(request, p):
    p = Product.objects.get(name=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, product=p)

        cart.delete()
    except:
        pass
    return redirect('cart:cartview')


def orderform(request):
    if (request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)


        #total amount
        total=0
        for i in cart:
            total+=i.quantity*i.product.price

        #check whether user has sufficient amount in account-
        ac=Account.objects.get(acctnum=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:#creates record in order table for each object in cart table for the current user
                o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()#clear the cart items for current user
            msg="Order Placed Successfully"
            return render(request,'orderdetail.html',{'m':msg})
        else:
            msg="Insufficient Amount in user Account.You cannot place order."
    return render(request,'orderform.html')
def orderview(request):
    u= request.user
    o=  Order.objects.filter(user=u)
    return render(request,'orderview.html',{'u':u.username,'o':o})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def search(request):
    q=""
    product=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q)| Q(desc__icontains=q))
    return render(request, 'search.html',{'p':product,'query':q})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html', {'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})
def detail(request,p):
    product=Product.objects.get(name=p)

    return render(request,'detail.html',{'p':product})

def register(request):
    if request.method == "POST":
        u = request.POST['u']
        p = request.POST['p']
        cp =request.POST['cp']
        e  =request.POST['e']


        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e)
            u.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("Password Not Matching")

    return render(request,'register.html')
def user_login(request):
    if request.method=="POST":
        name=request.POST['u']
        pass1=request.POST['p']
        user=authenticate(username=name,password=pass1)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            messages.error(request,"Invalid Credentials")
    return render(request,'login.html')


@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Freshcart</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<link href="https://raw.githubusercontent.com/daneden/animate.css/master/animate.css" rel="stylesheet"/>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</head>

<header>
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light  w-100" style="background-color: #cfebaf;">
	   <img class="image" src="{% static 'images/logo.png' %}" alt="logo" style="height: 50px; width:50px;">
    <a class="navbar-brand" href="{% url 'shop:allcat' %}" style="color:rgb(10 125 15);font-weight:700;">FreshCart</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>{% endfor %}

          </ul>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}">
            <i class="fa-solid fa-cart-shopping"></i>&nbsp;&nbsp;<sub>{{count}}</sub>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </nav>
</div>

</header>

{% block content %}
{% endblock %}
<footer>
    	<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-6">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href=""><i class="fa fa-angle-double-right"></i>Home</a></li>
						<li><a href=""><i class="fa fa-angle-double-right"></i>About</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-6">
					<h5>Contact</h5>
					<ul class="list-unstyled quick-links">
						<li><a href=""><i class="fa fa-angle-double-right"></i>Email</a></li>
						<li><a href=""><i class="fa fa-angle-double-right"></i>Phone number</a></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="https://www.fiverr.com/share/qb8D02"><i class="fa-brands fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href="https://www.fiverr.com/share/qb8D02"><i class="fa-brands fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="https://www.fiverr.com/share/qb8D02"><i class="fa-brands fa-x-twitter"></i></a></li>
					</ul>

				</div>
				<hr>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p class="h6">© All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Freshcart</a></p>
				</div>
				<hr>
			</div>
		</div>
	</section>
</footer>
</html>

ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not c %}
<div class="container-fluid mt-3">
    <h3 class="text-center">Cart is empty</h3>
    <h5 class="text-center text-success"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h5>
</div>

{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h4 class="text-center">SHOPPING CART</h4>


    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr><th colspan="5" class="text-center">CART ITEMS</th></tr>
            {% for i in c %}
        <tr><td><img src="{{i.product.image.url}}" height="150px" width="150px"</td>
            <td><b>{{i.product.name}}</b></td>
            <td><b>Product id:{{i.product.id}}</b><br>
            <b>UnitPrice:{{i.product.price}}</b><br>
            <b>Quantity:{{i.quantity}}*{{i.product.price}}</b></td>

            <td>Subtotal:{{i.subtotal}}</td>
            <td>
                {% if i.quantity < i.product.stock %}
               <b><a href="{% url 'cart:addtocart' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-plus"></i></a>
            <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-minus"></i></a>
            <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-trash-can"></i></a></td></b>
{% else %}
             <b></b><a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-minus"></i></a>
            <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-trash-can"></i></a></td></b>
        </tr>
        {% endif %}
 {% endfor %}
        </table>
    </div>

    <div class="col-sm-4" style="position:relative">
        <table class="table table-bordered">
        <tr><th colspan="4" class="text-center">CHECK OUT</th></tr>
            <tr><td class="text-center"><b>TOTAL: <span class="text-danger">{{total}}</span></b></td></tr>
        </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-primary text-dark"><b>Place Order</b></a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-primary text-dark" style="position:absolute;right:0;"><b>Continue Shopping</b></a>
    </div>

</div>
</div>
{% endif %}
  {% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--    <img src="{% static 'images/banner.png' %}" height="500px" width="100%" >-->

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="container-fluid">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/img_1.png' %}" height="500px" width="100%" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h1 class="banner_title">Shop Smart, Eat Fresh</h1>
        <p>Experience the ease of grocery shopping from home.</p>
      </div>
    </div>
    <div class="carousel-item">
     <img src="{% static 'images/img_4.jpg' %}" height="500px" width="100%" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h1  class="banner_title">Fresh finds to your door.</h1>
        <p>Quality ingredients, sourced fresh and delivered to your door.</p>
      </div>
    </div>
    <div class="carousel-item">
     <img src="{% static 'images/img_2.png' %}" height="500px" width="100%" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h1  class="banner_title">One Click, Fresh Picks </h1>
        <p>Fast, reliable delivery of your favorite fresh groceries.</p>
      </div>
    </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
    </div>



<section class="about_area_4 pt-80 pb-130">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-lg-6">
                    <div class="about_image_5 mt-50">
                        <img class="image" src="{% static 'images/about.png' %}" alt="about">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6">
                    <div class="about_content_5 text-center mt-45">
                        <div class="section_title">
                            <h2 class="title">WELCOME</h2>
                            <p class="details">Welcome to our online grocery shop, where quality meets convenience! We are dedicated to bringing you the freshest produce, premium meats, and wholesome pantry staples, all sourced with care and delivered right to your door. Our passion for quality and nutrition drives us to offer a diverse selection, ensuring every meal is delicious and nourishing. Join us on this journey to elevate your culinary experience with the finest ingredients!.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


<!-- Featurs Section Start -->

<section class="our-webcoderskull padding-lg">
  <div class="container">
    <div class="row heading heading-icon">
        <h2>Our Special Features</h2>
    </div>
    <ul class="row">
      <li class="col-12 col-md-12 col-lg-4">
          <div class="cnt-block equal-hight" style="height: 300px;">
            <figure><img src="{% static 'images/pack.png' %}" class="img-responsive" alt=""></figure>
            <h3>Hygienically Packed</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do dunt ut labore.</p>

          </div>
      </li>
      <li class="col-12 col-md-12 col-lg-4">
          <div class="cnt-block equal-hight" style="height: 300px;">
            <figure><img src="{% static 'images/delivery.png' %}" class="img-responsive" alt=""></figure>
            <h3>Fast & Easy Grocery Delivery </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do dunt ut labore.</p>
          </div>
      </li>
      <li class="col-12 col-md-12 col-lg-4">
          <div class="cnt-block equal-hight" style="height: 300px;">
            <figure><img src="{% static 'images/veg.png' %}" class="img-responsive" alt=""></figure>
            <h3>Fresh Organic Vegetable</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do dunt ut labore.</p>
          </div>
       </li>
    </ul>
  </div>
</section>



<!--categories area-->

       <div class="container" >
           <div class="row">
                <h2 class="title">OUR PRODUCTS</h2>
               {% for i in c%}
               <div class="col-12 col-md-6 col-lg-3">
                   <div class="card">
                      <img src="{{i.image.url}}" class="card-img-top" alt="..." height="200px;"  >
                      <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary">Shop Now</a>
                      </div>
                   </div>
               </div>
               {% endfor %}
           </div>
       </div>

<section >
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="slider_content_3 text-center">
                        <h2 class="main_title">Top Sellers</h2>

                        <div class="slider_box_wrapper d-flex flex-wrap justify-content-between">
                            <div class="single_column" style="background-color: #f3e6e6; border-radius: 20px;">
                                <div class="single_box">
                                    <img src="{% static 'images/orange.png' %}">
                                    <h5>Orange</h5>
                                </div>
                            </div>
                            <div class="single_column" style="background-color: #f3e6e6;border-radius: 20px;">
                                <div class="single_box">
                                    <img src="{% static 'images/walnut.png' %}" >
                                    <h5>Walnut</h5>
                                </div>
                            </div>
                            <div class="single_column" style="background-color: #f3e6e6;border-radius: 20px;">
                                <div class="single_box">
                                    <img src="{% static 'images/icecream.png' %}" >
                                    <h5>Icecream</h5>

                                </div>
                            </div>
                            <div class="single_column" style="background-color: #f3e6e6;border-radius: 20px;">
                                <div class="single_box">
                                    <img src="{% static 'images/blueberry.png' %}" >
                                    <h6>Blueberry</h6>

                                </div>
                            </div>
                            <div class="single_column" style="background-color: #f3e6e6;border-radius: 20px;">
                                <div class="single_box">
                                    <img src="{% static 'images/caps.png' %}" >
                                    <h5>Capsicum</h5>
                                </div>
                            </div>
                            <div class="single_column" style="background-color: #f3e6e6;border-radius: 20px;">
                                <div class="single_box">
                                    <img src="{% static 'images/strawberry.png' %}" >
                                    <h5>Strawberry</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>





{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4" style="margin-bottom:60px;margin-left:250px;">
    <div class="container">
    <div class="row">
        <div class="col-12 col-lg-6"><img src="{{p.image.url}}" height="300px" width="370px"></div>
        <div class="col-12 col-lg-4">
            <h4>{{p.name}}</h4>
            <h5 class="mt-2">{{p.price}}</h5>
            {{p.stock}}
            <p class="mt-2" style="text-indent:20px;line-height:1.8;text-align:justify">{{p.desc}}</p>

            {% if user.is_superuser == False %}


            {% if p.stock <= 0%}
            <h4>Out of Stock</h4>
            {% else %}

            <h4><a href="{% url 'cart:addtocart' p.name %}" class="btn btn-secondary mt-4">Add To Cart</a></h4>
            {% endif %}

            {% else %}
            {% if p.stock <= 0%}
            <h4>Out of Stock</h4>

            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>
            {% else %}
             <h4>Product in Stock</h4>
            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>


            {% endif %}
                {% endif %}
        </div>
    </div>
    </div>
</div>


  {% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4" style="margin-bottom:60px;">
    <div class="d-flex justify-content-center">
    <img src="{{c.image.url}}"  class="circular-image" width="10cd0%" height="450px">
    </div>
</div>

<div class="container mt-1" style="margin-bottom:60px;">
    <h3 class="text-center fw-bold pb-3"> {{c.name}}</h3>
    <p style="line-height:2;text-align:justify;"> {{c.desc}} </p>
</div>
<div class="container" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-12 col-md-6 col-lg-3">
            <div class="card" >
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="200px" width="100%;">
  <div class="card-body" >
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5 class="text-center">{{i.price}}</h5>
    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:38%; bottom:30%;">DETAILS</a>
  </div>
</div>

        </div>{% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="text-center"><h4>You Have Searched for <span class="text-success fw-bolder">{{query}}</span></h4></div>
</center>
<div class="container mt-2 rounded rounded-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-12 col-md-6 col-lg-3">
            <div class="card mb-4">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="200px" width="100%;">
  <div class="card-body" >
    <h5 class="card-title text-center">{{i.name}}</h5>
      <h5 class="text-center">{{i.price}}</h5>
    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">DETAILS</a>
  </div>
</div>

        </div>
{% empty %}
        <h4 class="text-center text-danger">No Search Results Found</h4>
        {% endfor %}
    </div>
</div>


  {% endblock %}